/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

type format = "png" | "jpg" | "jpeg" | "bmp" | "gif" | "tiff" | "webp";
declare module "img-converter" {
  export function convertImageFile(inputData: Buffer, format: format): Buffer;
}
